blank_issues_enabled: true
contact_links:
  - name: Bug Report
    url: https://github.com/Ratnadeepdeyroy/ratnosint7/issues/new?template=bug_report.yml
    about: Report a bug
  - name: Feature Request
    url: https://github.com/Ratnadeepdeyroy/ratnosint7/issues/new?template=feature_request.yml
    about: Request a feature
